version: '3.7'
services:
  node:
    container_name: api
    build:
      context: .
      target: app_development
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    ports:
      - 3000:3000
    volumes:
      - ./:/app
